image:  docker:19.03.12

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""

services:
  - name: docker:19.03.12-dind
    entrypoint: ["env", "-u", "DOCKER_HOST"]
    command: ["dockerd-entrypoint.sh"]

before_script:
  - docker login -u $REGISTRY_USERNAME -p $USER_TOKEN $CI_REGISTRY

stages:
  - build


bot:latest:
  stage: build
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
      when: on_success
  script:
    - |
      docker build --pull -t "$CI_REGISTRY_IMAGE/bot:latest" .
      docker push "$CI_REGISTRY_IMAGE/bot:latest"


redis:latest:
  stage: build
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
      when: on_success
  script:
    - |
      docker build --pull -t "$CI_REGISTRY_IMAGE/redis-custom:latest" redis_build/
      docker push "$CI_REGISTRY_IMAGE/redis-custom:latest"


bot:tagged:
  stage: build
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v([0-9.]+)$/'
      when: on_success
  script:
    - |
      docker pull "$CI_REGISTRY_IMAGE/bot:latest"
      docker tag "$CI_REGISTRY_IMAGE/bot:latest" "$CI_REGISTRY_IMAGE/bot:$CI_COMMIT_TAG"
      docker push "$CI_REGISTRY_IMAGE/bot:$CI_COMMIT_TAG"


redis:tagged:
  stage: build
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v([0-9.]+)$/'
      when: on_success
  script:
    - |
      docker pull "$CI_REGISTRY_IMAGE/redis-custom:latest"
      docker tag "$CI_REGISTRY_IMAGE/redis-custom:latest" "$CI_REGISTRY_IMAGE/redis-custom:$CI_COMMIT_TAG"
      docker push "$CI_REGISTRY_IMAGE/redis-custom:$CI_COMMIT_TAG"
