version: "3.8"
services:
    bot:
        # Универсальный образ для x86/ARM64
        image: groosha/telegram-casino-bot:latest
        restart: "always"
        stop_signal: SIGINT
        volumes:
            # Путь к .env файлу с настройками
            - "/home/user/casino-bot-redis/.env:/app/.env"
        depends_on:
            - redis
    redis:
        image: redis:7
        restart: "always"
        volumes:
            # Путь к каталогу с redis.conf
            - "/home/user/casino-bot-redis/redis_config:/usr/local/etc/redis"
            # Путь к каталогу, где будет лежать дамп базы Redis
            - "/home/user/casino-bot-redis/redis_data:/data"
        command: "redis-server /usr/local/etc/redis/redis.conf"
