version: "3.8"
services:
    bot:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: "telegram-casino-bot"
        restart: unless-stopped
        environment:
            - BOT_TOKEN=${BOT_TOKEN}
        depends_on:
            - redis
    redis:
        image: redis:6.0-alpine
        container_name: "telegram-casino-redis"
        hostname: redis
        volumes:
            - "redis_config:/usr/local/etc/redis"
            - "redis_data:/data"
        command: "redis-server /usr/local/etc/redis/redis.conf"

volumes:
    redis_config:
        driver: local
        driver_opts:
            type: 'none'
            o: 'bind'
            device: './config'
    redis_data:
        driver: local
        driver_opts:
            type: 'none'
            o: 'bind'
            device: './redis-data'
